export type Organization = { id: string; name: string; creditBalanceMicros: string; role: 'OWNER' | 'ADMIN' | 'EDITOR' | 'VIEWER' };
export type Me = { profile: { id: string; email: string; displayName?: string; platformRole: 'USER' | 'PLATFORM_ADMIN' }; organizations: Organization[] };
export type WordPressCompatibilityMode = 'RECHECK_REQUIRED' | 'FULL_AUTO' | 'SAFE_AUTO' | 'ANALYSIS_ONLY' | 'BLOCKED';
export type Site = { id: string; name: string; domain: string; language: string; wordpressStatus: string; wordpressUser?: string; wordpressVerifiedAt?: string; wordpressCompatibilityMode: WordPressCompatibilityMode; wordpressCompatibilityCheckedAt?: string; createdAt: string; integrations: Array<{ id: string; provider: 'GSC'; propertyId?: string; status: string; lastSyncedAt?: string; lastErrorMessage?: string }> };
export type Opportunity = { id: string; siteId: string; title: string; type: string; targetUrl?: string; keyword?: string; searchVolume?: number; keywordDifficulty?: number; allintitleCount?: number; roiScoreMicros?: string; expectedValueMicros?: string; confidenceMicros?: string; formulaVersion: string; status: string };
export type GrowthStageCode = 'UNDERSTAND' | 'DISCOVER' | 'DECIDE' | 'EXECUTE' | 'LEARN';
export type GrowthRunStage = {
  id: string;
  runId: string;
  siteId: string;
  stage: GrowthStageCode;
  status: 'PENDING' | 'RUNNING' | 'COMPLETED' | 'SKIPPED' | 'BLOCKED' | 'FAILED';
  summary?: string;
  processedCount: number;
  totalCount?: number;
  evidence: Array<Record<string, unknown>>;
  errorCode?: string;
  errorMessage?: string;
  startedAt?: string;
  finishedAt?: string;
  updatedAt?: string;
};
export type GrowthAction = {
  id: string;
  runId: string;
  type: string;
  status: string;
  riskLevel: 'A' | 'B' | 'C' | 'D';
  autonomyDecision: 'AUTO_EXECUTE' | 'REQUIRE_REVIEW' | 'REJECT';
  targetUrl?: string;
  expectedValueMicros?: string;
  plan: Record<string, unknown>;
  evidence?: ActionEvidence[];
  pageVersions?: PageVersion[];
  measurements?: MeasurementSample[];
  createdAt: string;
  decision?: { rank: number; scoreMicros: string; rationale: Record<string, unknown> };
};
export type ActionEvidence = { id: string; type: string; sourceRef?: string; payload: Record<string, unknown>; createdAt: string };
export type PageVersion = { id: string; kind: 'BEFORE' | 'AFTER' | 'ROLLBACK'; remotePostId: string; resourceType: string; url: string; title: string; contentChecksum: string; remoteModifiedAt?: string; createdAt: string };
export type MeasurementSample = { id: string; source: 'GSC' | 'LEADING_INDICATORS'; windowDays: 7 | 14 | 28 | 56; baseline: Record<string, unknown>; measurement: Record<string, unknown>; confidenceMicros: string; outcome: 'NOT_READY' | 'WIN' | 'NEUTRAL' | 'LOSS' | 'INCONCLUSIVE'; observedAt: string };
export type SiteSnapshotSummary = { id: string; status: string; sourceVersion: string; market: Record<string, unknown>; health: Record<string, unknown>; corpusChecksum: string; pageCount: number; auditedPageCount: number; fetchedAt: string; pages?: Array<{ id: string; url: string; resourceType: string; status: string; modifiedAt?: string; title: string; wordCount: number; contentChecksum: string; technicalEvidence: Record<string, unknown> }> };
export type GrowthCandidate = { id: string; status: 'PROPOSED' | 'SELECTED' | 'DEFERRED' | 'REJECTED' | 'EXECUTED'; rank: number; scoreMicros: string; scoreVersion: string; rationale: Record<string, unknown>; opportunity: Opportunity; action?: Pick<GrowthAction, 'id' | 'type' | 'status' | 'targetUrl'> };
export type GrowthInputType = 'KEYWORD' | 'REFERENCE_URL' | 'COMPETITOR_SITE';
export type GrowthInput = {
  id?: string;
  type: GrowthInputType;
  value: string;
  normalizedValue?: string;
  position?: number;
};
export type GrowthProgram = {
  id: string;
  siteId: string;
  mode: 'ONCE' | 'CONTINUOUS';
  inputs: GrowthInput[];
  status: 'ACTIVE' | 'PAUSED' | 'COMPLETED' | 'BLOCKED';
  nextRunAt?: string;
  lastRunAt?: string;
  deliveredRunCount: number;
  consecutiveWins: number;
  lastError?: string;
  createdAt: string;
  runs?: GrowthRun[];
};
export type JobRun = {
  id: string;
  type: string;
  status: 'QUEUED' | 'RUNNING' | 'SUCCEEDED' | 'FAILED' | 'DEAD_LETTER';
  result?: { resultId?: string };
  errorCode?: string;
  errorMessage?: string;
  createdAt: string;
  finishedAt?: string;
};
export type GrowthRun = {
  id: string;
  siteId: string;
  programId: string;
  jobRunId?: string;
  trigger: 'USER' | 'SCHEDULED' | 'DATA_CHANGE' | 'OBSERVATION';
  status: 'QUEUED' | 'RUNNING' | 'NEEDS_REVIEW' | 'DELIVERED' | 'BLOCKED' | 'FAILED' | 'CANCELLED';
  currentStage: GrowthStageCode;
  resolvedKeyword?: string;
  selectedActionType?: string;
  targetUrl?: string;
  opportunityId?: string;
  draftId?: string;
  delivery?: Record<string, unknown>;
  observation?: Record<string, unknown>;
  errorCode?: string;
  errorMessage?: string;
  stages: GrowthRunStage[];
  actions?: GrowthAction[];
  draft?: Draft;
  siteSnapshot?: SiteSnapshotSummary;
  measurement?: { gscConnected: boolean; lastSyncedAt?: string; trafficClaimAllowed: boolean };
  createdAt: string;
  updatedAt: string;
};
export type GrowthStatus = {
  program: GrowthProgram | null;
  run: GrowthRun | null;
  action: GrowthAction | null;
  stages: GrowthRunStage[];
  blocker: { code: string; message?: string } | null;
  measurement: { gscConnected: boolean; lastSyncedAt?: string; trafficClaimAllowed: boolean; targetUrl?: string };
  wordpressCompatibility: { mode: WordPressCompatibilityMode; profileId?: string; supportedActions: string[]; blockedActions: string[]; fallbackReason?: string; blockReasons: string[]; lastCheckedAt?: string; expiresAt?: string };
};
export type Draft = {
  id: string;
  siteId: string;
  opportunityId?: string;
  title: string;
  status: string;
  html: string;
  qualityReport: { passed?: boolean; score?: number; issues?: string[]; passedChecks?: string[] };
  dataProvenance?: Array<{ source?: string; status?: string }>;
  knowledgeSourceIds?: string[];
  publishedUrl?: string;
  createdAt?: string;
  reviews: Array<{ decision: string; comment?: string }>;
  publishAttempts: Array<{ status: string; remoteUrl?: string; errorMessage?: string }>;
};
export type Ledger = { balanceMicros: string; heldMicros: string; availableMicros: string; entries: Array<{ id: string; type: string; amountMicros: string; balanceAfterMicros: string; reason: string; createdAt: string }> };
