import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState, type FormEvent } from 'react';
import { api } from '../lib/api';
import type { Draft, JobRun, KnowledgeSource, Opportunity, Site } from '../types/api';
import { useWorkspace } from '../workspace/WorkspaceContext';

export default function ContentPage() {
  const { organization } = useWorkspace(); const queryClient = useQueryClient(); const base = `/organizations/${organization.id}`;
  const sites = useQuery({ queryKey: ['sites', organization.id], queryFn: () => api.get<Site[]>(`${base}/sites`).then(({ data }) => data) });
  const knowledge = useQuery({ queryKey: ['knowledge', organization.id], queryFn: () => api.get<KnowledgeSource[]>(`${base}/knowledge-sources?limit=100`).then(({ data }) => data) });
  const opportunities = useQuery({ queryKey: ['opportunities', organization.id], queryFn: () => api.get<Opportunity[]>(`${base}/opportunities?limit=100`).then(({ data }) => data), refetchInterval: 15_000 });
  const jobs = useQuery({ queryKey: ['jobs', organization.id], queryFn: () => api.get<JobRun[]>(`${base}/jobs?limit=30`).then(({ data }) => data), refetchInterval: 8_000 });
  const drafts = useQuery({ queryKey: ['drafts', organization.id], queryFn: () => api.get<Draft[]>(`${base}/drafts`).then(({ data }) => data), refetchInterval: 10_000 });
  const refresh = () => Promise.all(['knowledge', 'opportunities', 'jobs', 'drafts'].map((key) => queryClient.invalidateQueries({ queryKey: [key, organization.id] })));
  return <section className="space-y-6"><div><h1 className="page-title">真实数据内容流水线</h1><p className="muted">数据快照 → 机会 → 客户知识 → AI 草稿 → 确定性门禁 → 审批 → WordPress。</p></div><div className="grid gap-6 xl:grid-cols-2"><KnowledgeForm base={base} sites={sites.data || []} onChanged={refresh} /><ScanForm base={base} sites={sites.data || []} onChanged={refresh} /></div><OpportunityPanel base={base} opportunities={opportunities.data || []} knowledge={knowledge.data || []} onChanged={refresh} /><DraftPanel base={base} drafts={drafts.data || []} onChanged={refresh} /><article className="panel"><h2 className="section-title">任务状态</h2><div className="table-wrap"><table><thead><tr><th>任务</th><th>状态</th><th>错误</th></tr></thead><tbody>{jobs.data?.map((job) => <tr key={job.id}><td>{job.type}</td><td>{job.status}</td><td className="text-rose-300">{job.errorMessage || '—'}</td></tr>)}</tbody></table></div></article></section>;
}

function KnowledgeForm({ base, sites, onChanged }: { base: string; sites: Site[]; onChanged: () => Promise<unknown> }) {
  const [type, setType] = useState<'TEXT' | 'ORIGINAL_RESEARCH' | 'ALLOWLISTED_URL'>('TEXT'); const [siteId, setSiteId] = useState(''); const [title, setTitle] = useState(''); const [content, setContent] = useState(''); const [sourceUrl, setSourceUrl] = useState(''); const [message, setMessage] = useState('');
  const mutation = useMutation({ mutationFn: () => api.post(`${base}/knowledge-sources`, type === 'ALLOWLISTED_URL' ? { type, siteId: siteId || undefined, title, sourceUrl } : { type, siteId: siteId || undefined, title, content }), onSuccess: async () => { setTitle(''); setContent(''); setSourceUrl(''); setMessage('知识来源已持久化并去重。'); await onChanged(); }, onError: (error) => setMessage(error instanceof Error ? error.message : '保存失败') });
  return <form className="panel space-y-3" onSubmit={(event) => { event.preventDefault(); mutation.mutate(); }}><h2 className="section-title">添加知识来源</h2><div className="grid gap-3 sm:grid-cols-2"><select className="field" value={type} onChange={(event) => setType(event.target.value as typeof type)}><option value="TEXT">客户文本</option><option value="ORIGINAL_RESEARCH">原创研究</option><option value="ALLOWLISTED_URL">白名单 URL</option></select><select className="field" value={siteId} onChange={(event) => setSiteId(event.target.value)}><option value="">组织通用</option>{sites.map((site) => <option key={site.id} value={site.id}>{site.name}</option>)}</select></div><input className="field" placeholder="标题" value={title} onChange={(event) => setTitle(event.target.value)} required />{type === 'ALLOWLISTED_URL' ? <input className="field" type="url" placeholder="https://..." value={sourceUrl} onChange={(event) => setSourceUrl(event.target.value)} required /> : <textarea className="field min-h-32" placeholder="至少 40 个字符" value={content} onChange={(event) => setContent(event.target.value)} required />}<button className="primary" disabled={mutation.isPending}>保存来源</button>{message && <p className="text-sm text-cyan-200">{message}</p>}</form>;
}

function ScanForm({ base, sites, onChanged }: { base: string; sites: Site[]; onChanged: () => Promise<unknown> }) {
  const [siteId, setSiteId] = useState(''); const [seedKeyword, setSeedKeyword] = useState(''); const [message, setMessage] = useState('');
  const scan = useMutation({ mutationFn: () => api.post(`${base}/keyword-scans`, { siteId, seedKeyword, languageCode: 'zh_CN', locationCode: 2156 }), onSuccess: async () => { setSeedKeyword(''); setMessage('真实数据扫描已进入队列。'); await onChanged(); }, onError: (error) => setMessage(error instanceof Error ? error.message : '创建失败') });
  return <form className="panel space-y-3" onSubmit={(event: FormEvent) => { event.preventDefault(); scan.mutate(); }}><h2 className="section-title">DataForSEO 扫描</h2><select className="field" value={siteId} onChange={(event) => setSiteId(event.target.value)} required><option value="">选择站点</option>{sites.map((site) => <option key={site.id} value={site.id}>{site.name}</option>)}</select><input className="field" placeholder="种子关键词" value={seedKeyword} onChange={(event) => setSeedKeyword(event.target.value)} required /><p className="muted text-sm">当前默认中文、位置代码 2156。任务会真实扣除计价项积分。</p><button className="primary" disabled={scan.isPending}>创建扫描</button>{message && <p className="text-sm text-cyan-200">{message}</p>}</form>;
}

function OpportunityPanel({ base, opportunities, knowledge, onChanged }: { base: string; opportunities: Opportunity[]; knowledge: KnowledgeSource[]; onChanged: () => Promise<unknown> }) {
  const [selectedKnowledge, setSelectedKnowledge] = useState<string[]>([]); const [message, setMessage] = useState('');
  const create = useMutation({ mutationFn: (opportunity: Opportunity) => api.post(`${base}/content-runs`, { siteId: opportunity.siteId, opportunityId: opportunity.id, knowledgeSourceIds: selectedKnowledge }), onSuccess: async () => { setMessage('内容任务已创建。'); await onChanged(); }, onError: (error) => setMessage(error instanceof Error ? error.message : '创建失败') });
  return <article className="panel space-y-4"><h2 className="section-title">机会与内容任务</h2><div className="flex flex-wrap gap-2">{knowledge.map((source) => <label key={source.id} className="chip"><input type="checkbox" checked={selectedKnowledge.includes(source.id)} onChange={(event) => setSelectedKnowledge((current) => event.target.checked ? [...current, source.id] : current.filter((id) => id !== source.id))} />{source.title}</label>)}</div><div className="table-wrap"><table><thead><tr><th>关键词</th><th>搜索量</th><th>KD</th><th>allintitle</th><th>数据状态</th><th /></tr></thead><tbody>{opportunities.map((item) => <tr key={item.id}><td>{item.keyword}</td><td>{item.searchVolume}</td><td>{item.keywordDifficulty}</td><td>{item.allintitleCount}</td><td>{item.formulaVersion}</td><td><button className="secondary" disabled={!selectedKnowledge.length || create.isPending} onClick={() => create.mutate(item)}>生成草稿</button></td></tr>)}</tbody></table></div>{opportunities.length === 0 && <p className="empty">尚无真实机会数据</p>}{message && <p className="text-sm text-cyan-200">{message}</p>}</article>;
}

function DraftPanel({ base, drafts, onChanged }: { base: string; drafts: Draft[]; onChanged: () => Promise<unknown> }) {
  const [comments, setComments] = useState<Record<string, string>>({}); const [message, setMessage] = useState('');
  const action = useMutation({ mutationFn: ({ draft, name }: { draft: Draft; name: 'approve' | 'reject' | 'publish' | 'rollback' }) => api.post(`${base}/drafts/${draft.id}/${name}`, name === 'reject' ? { comment: comments[draft.id] || '' } : { comment: comments[draft.id] || undefined }), onSuccess: async () => { setMessage('草稿状态已更新。'); await onChanged(); }, onError: (error) => setMessage(error instanceof Error ? error.message : '操作失败') });
  return <article className="panel space-y-4"><h2 className="section-title">草稿审批与发布</h2>{drafts.map((draft) => <details key={draft.id} className="rounded-xl border border-slate-800 p-4"><summary className="cursor-pointer font-semibold">{draft.title} <span className="status ml-2">{draft.status}</span></summary><div className="mt-4 space-y-3"><div className="prose-preview" dangerouslySetInnerHTML={{ __html: draft.html }} /><p className="muted">质量门禁：{draft.qualityReport.passed ? `通过 (${draft.qualityReport.score ?? '—'})` : '未通过'}</p><input className="field" placeholder="审批意见；拒绝时必填" value={comments[draft.id] || ''} onChange={(event) => setComments((current) => ({ ...current, [draft.id]: event.target.value }))} /><div className="flex flex-wrap gap-2">{draft.status === 'PENDING_REVIEW' && <><button className="primary" onClick={() => action.mutate({ draft, name: 'approve' })}>批准</button><button className="danger" disabled={!comments[draft.id]} onClick={() => action.mutate({ draft, name: 'reject' })}>拒绝</button></>}{draft.status === 'APPROVED' && <button className="primary" onClick={() => action.mutate({ draft, name: 'publish' })}>发布到 WordPress</button>}{draft.status === 'PUBLISHED' && <><a className="secondary" href={draft.publishedUrl} target="_blank" rel="noreferrer">查看文章</a><button className="danger" onClick={() => action.mutate({ draft, name: 'rollback' })}>远端回滚</button></>}</div></div></details>)}{drafts.length === 0 && <p className="empty">暂无草稿</p>}{message && <p className="text-sm text-cyan-200">{message}</p>}</article>;
}
