import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState, type FormEvent } from 'react';
import { api } from '../lib/api';
import type { Site } from '../types/api';
import { useWorkspace } from '../workspace/WorkspaceContext';

export default function SitesPage() {
  const { organization } = useWorkspace();
  const queryClient = useQueryClient();
  const base = `/organizations/${organization.id}`;
  const sites = useQuery({ queryKey: ['sites', organization.id], queryFn: () => api.get<Site[]>(`${base}/sites`).then(({ data }) => data) });
  const [name, setName] = useState(''); const [domain, setDomain] = useState(''); const [message, setMessage] = useState('');
  const refresh = () => queryClient.invalidateQueries({ queryKey: ['sites', organization.id] });
  const create = useMutation({ mutationFn: () => api.post(`${base}/sites`, { name, domain, language: 'zh-CN' }), onSuccess: async () => { setName(''); setDomain(''); await refresh(); }, onError: (error) => setMessage(error instanceof Error ? error.message : '创建失败') });
  const submit = (event: FormEvent) => { event.preventDefault(); setMessage(''); create.mutate(); };
  return <section className="space-y-6"><div><h1 className="page-title">WordPress 站点</h1><p className="muted">仅支持公网 HTTPS WordPress。凭证加密存储，保存后不会回传。</p></div><form onSubmit={submit} className="panel grid gap-4 md:grid-cols-[1fr_1fr_auto] items-end"><label>站点名称<input className="field" value={name} onChange={(event) => setName(event.target.value)} required /></label><label>域名<input className="field" placeholder="example.com" value={domain} onChange={(event) => setDomain(event.target.value)} required /></label><button className="primary" disabled={create.isPending}>添加站点</button>{message && <p className="error-text md:col-span-3">{message}</p>}</form><div className="grid gap-5 lg:grid-cols-2">{sites.data?.map((site) => <SiteCard key={site.id} site={site} base={base} onChanged={refresh} />)}</div>{sites.data?.length === 0 && <div className="panel empty">尚未添加站点</div>}</section>;
}

function SiteCard({ site, base, onChanged }: { site: Site; base: string; onChanged: () => Promise<unknown> }) {
  const [username, setUsername] = useState(''); const [applicationPassword, setApplicationPassword] = useState(''); const [gscProperty, setGscProperty] = useState(`sc-domain:${site.domain}`); const [message, setMessage] = useState('');
  const credentials = useMutation({ mutationFn: () => api.put(`${base}/sites/${site.id}/wordpress-credentials`, { username, applicationPassword }), onSuccess: async () => { setApplicationPassword(''); setMessage('凭证已加密保存，请执行连接测试。'); await onChanged(); }, onError: (error) => setMessage(error instanceof Error ? error.message : '保存失败') });
  const test = useMutation({ mutationFn: () => api.post<{ connected: boolean; user: string }>(`${base}/sites/${site.id}/test-connection`, {}), onSuccess: async ({ data }) => { setMessage(`连接成功：${data.user}`); await onChanged(); }, onError: (error) => setMessage(error instanceof Error ? error.message : '连接失败') });
  const auto = useMutation({ mutationFn: (enabled: boolean) => api.post(`${base}/sites/${site.id}/auto-publish`, { enabled, acceptRisk: enabled }), onSuccess: async () => { setMessage('发布策略已更新'); await onChanged(); }, onError: (error) => setMessage(error instanceof Error ? error.message : '策略更新失败') });
  const gscAuthorize = useMutation({ mutationFn: () => api.post<{ authorizationUrl: string }>(`${base}/sites/${site.id}/gsc/authorize`, { propertyId: gscProperty }), onSuccess: ({ data }) => window.location.assign(data.authorizationUrl), onError: (error) => setMessage(error instanceof Error ? error.message : 'GSC 授权失败') });
  const gscSync = useMutation({ mutationFn: () => { const end = new Date(Date.now() - 3 * 86_400_000); const start = new Date(end.getTime() - 27 * 86_400_000); return api.post(`${base}/sites/${site.id}/gsc/sync`, { startDate: start.toISOString().slice(0, 10), endDate: end.toISOString().slice(0, 10) }); }, onSuccess: async () => { setMessage('GSC 真实数据同步已进入队列。'); await onChanged(); }, onError: (error) => setMessage(error instanceof Error ? error.message : 'GSC 同步失败') });
  const gsc = site.integrations.find(({ provider }) => provider === 'GSC');
  return <article className="panel space-y-4"><div className="flex justify-between gap-3"><div><h2 className="section-title">{site.name}</h2><p className="muted">https://{site.domain}</p></div><span className="status">{site.wordpressStatus}</span></div><dl className="grid grid-cols-2 gap-2 text-sm"><div><dt className="muted">发布策略</dt><dd>{site.publishPolicy}</dd></div><div><dt className="muted">人工成功发布</dt><dd>{site.manualPublishSuccesses}/3</dd></div><div><dt className="muted">验证用户</dt><dd>{site.wordpressUser || '未采集'}</dd></div><div><dt className="muted">验证时间</dt><dd>{site.wordpressVerifiedAt ? new Date(site.wordpressVerifiedAt).toLocaleString() : '未采集'}</dd></div></dl><div className="grid gap-3 sm:grid-cols-2"><input className="field" placeholder="WordPress 用户名" value={username} onChange={(event) => setUsername(event.target.value)} /><input className="field" type="password" placeholder="Application Password" value={applicationPassword} onChange={(event) => setApplicationPassword(event.target.value)} /></div><div className="flex flex-wrap gap-2"><button className="secondary" onClick={() => credentials.mutate()} disabled={!username || !applicationPassword || credentials.isPending}>更新凭证</button><button className="secondary" onClick={() => test.mutate()} disabled={test.isPending}>真实连接测试</button>{site.publishPolicy === 'AUTO_PUBLISH' ? <button className="danger" onClick={() => auto.mutate(false)}>关闭自动发布</button> : <button className="primary" onClick={() => auto.mutate(true)}>接受风险并尝试开启</button>}</div><div className="border-t border-slate-800 pt-4 space-y-2"><div className="flex justify-between"><strong>Google Search Console</strong><span className="status">{gsc?.status || '未配置'}</span></div><input className="field" value={gscProperty} onChange={(event) => setGscProperty(event.target.value)} placeholder="sc-domain:example.com" /><div className="flex gap-2"><button className="secondary" onClick={() => gscAuthorize.mutate()}>授权 GSC</button><button className="secondary" disabled={!gsc} onClick={() => gscSync.mutate()}>同步近 28 天真实数据</button></div><p className="muted text-xs">属性：{gsc?.propertyId || '未采集'}；上次同步：{gsc?.lastSyncedAt ? new Date(gsc.lastSyncedAt).toLocaleString() : '未采集'}</p></div>{message && <p className="text-sm text-cyan-200">{message}</p>}</article>;
}
